version: "3"
services:

  postgres_notes:
    image: postgres
    container_name: postgres_notes
    ports:
      - 5433:5432/tcp
    volumes:
      - ./db/note/000001_base.up.sql:/docker-entrypoint-initdb.d/init_notes.sql

  notes_api:
    build:
      context: ./
      args:
        - GO_APP_LOCATION=notes/api
      dockerfile: Dockerfile
    image: notes
    volumes:
      - cache:/go
    environment:
      - POSTGRESQL_ADDRESS=${POSTGRESQL_ADDRESS}
      - STAGE=${STAGE}
    ports:
      - 8000:8000
    depends_on:
      - postgres_notes
    #  - redis

volumes:
  cache: