version: "3"
services:

  web:
    image: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./swagger:/var/www/html
    environment:
      - EXPOSED_DOMAIN_NAME=${EXPOSED_DOMAIN_NAME}
    ports:
      - 80:80
      - 443:443
    command: /bin/bash -c "apt-get update && apt-get install openssl && envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && ENCODED_PASS=`echo ${API_WEB_HTTP_BASIC_AUTH_PASSWORD} | openssl passwd  -stdin` && echo ${API_WEB_HTTP_BASIC_AUTH_USER}:$${ENCODED_PASS} > /etc/nginx/htpasswd && exec nginx -g 'daemon off;'"
    depends_on:
      - redis
      - notes_api

  redis:
    image: redis

  postgres_notes:
    image: postgres
    container_name: postgres_notes
    ports:
      - 5433:5432/tcp
    volumes:
      - ./db/note/000001_base.up.sql:/docker-entrypoint-initdb.d/init_notes.sql

  notes_api:
    build:
      context: ./
      args:
        - GO_APP_LOCATION=notes/api
      dockerfile: Dockerfile
    image: notes
    volumes:
      - cache:/go
    environment:
      - POSTGRESQL_ADDRESS=${POSTGRESQL_ADDRESS_NOTES}
      - REDIS_ADDRESS=redis:6379
      - STAGE=${STAGE}
    ports:
      - 8000:8000/tcp
    depends_on:
      - postgres_notes
    #  - redis

volumes:
  cache: